# SPDX-License-Identifier: Apache-2.0
"""Plugin version, generated by setuptools-scm at build time."""

try:
    from vllm_sail._version import __version__, __version_tuple__
except Exception:  # pragma: no cover - source tree without a build
    import warnings

    warnings.warn(
        "vllm_sail._version is missing; falling back to a dev version. "
        "Install the package (`pip install -e .`) to generate it.",
        RuntimeWarning,
        stacklevel=2,
    )

    __version__ = "dev"
    __version_tuple__ = (0, 0, "dev")

__all__ = ["__version__", "__version_tuple__"]
