# SPDX-License-Identifier: Apache-2.0
"""Extend the existing MLA dataclass without replacing its class identity.

The runner calls dataclasses.replace before metadata construction. Add real
field descriptors as well as constructor/equality/hash handling so indexer
geometry survives replacement, grouping and merging. Keeping the same class
also preserves isinstance checks and by-value imports in preloaded consumers.
"""

from __future__ import annotations

from dataclasses import dataclass

from vllm.v1.kv_cache_interface import MLAAttentionSpec

from vllm_sail.patch.utils import patch

_AFFECTED = ">=0.30.0,<0.31.0"
_MODULE = "vllm.v1.kv_cache_interface"


@dataclass(frozen=True)
class _IndexerGeometry:
    indexer_n_head: int | None = None
    indexer_q_head_dim: int | None = None


# Dataclass field descriptors are generated by the standard library, including
# the init/default/type metadata consumed by replace(), fields() and asdict().
# Copy the mapping so a base class's fields are never mutated by inheritance.
MLAAttentionSpec.__dataclass_fields__ = {
    **MLAAttentionSpec.__dataclass_fields__,
    **_IndexerGeometry.__dataclass_fields__,
}
MLAAttentionSpec.__annotations__.update(_IndexerGeometry.__annotations__)

_upstream_spec_init = MLAAttentionSpec.__init__
_upstream_merge = MLAAttentionSpec.merge.__func__


@patch(
    _MODULE,
    "MLAAttentionSpec.__init__",
    reason=(
        "Fork adds indexer_n_head/indexer_q_head_dim fields to MLAAttentionSpec "
        "so the DeepseekV4 indexer cache can publish its geometry to the DSA "
        "indexer metadata builder. Field descriptors are extended alongside "
        "the generated constructor so dataclasses.replace retains them: "
        "it accepts the two extra kwargs, delegates the rest, and stores them "
        "via object.__setattr__."
    ),
    affected_versions=_AFFECTED,
    remove_when="upstream adds the indexer geometry fields to MLAAttentionSpec.",
)
def mla_attention_spec_init(
    self,
    *args,
    indexer_n_head: int | None = None,
    indexer_q_head_dim: int | None = None,
    **kwargs,
) -> None:
    _upstream_spec_init(self, *args, **kwargs)
    object.__setattr__(self, "indexer_n_head", indexer_n_head)
    object.__setattr__(self, "indexer_q_head_dim", indexer_q_head_dim)


@patch(
    _MODULE,
    "MLAAttentionSpec.merge",
    reason=(
        "Fork forwards indexer_n_head/indexer_q_head_dim through "
        "MLAAttentionSpec.merge (from specs[0], like the other geometry "
        "fields); DeepseekV32IndexerMetadataBuilder reads them off the merged "
        "group spec. Delegates to upstream merge, then copies the values from "
        "specs[0] onto the merged (frozen) spec."
    ),
    affected_versions=_AFFECTED,
    remove_when="upstream adds the indexer geometry fields to MLAAttentionSpec.",
)
def mla_attention_spec_merge(cls, specs):
    merged = _upstream_merge(cls, specs)
    first = specs[0]
    object.__setattr__(merged, "indexer_n_head", getattr(first, "indexer_n_head", None))
    object.__setattr__(
        merged, "indexer_q_head_dim", getattr(first, "indexer_q_head_dim", None)
    )
    return merged


_upstream_eq = MLAAttentionSpec.__eq__
_upstream_hash = MLAAttentionSpec.__hash__


@patch(
    _MODULE,
    "MLAAttentionSpec.__eq__",
    reason="Indexer geometry participates in KV spec grouping as in the PPU fork.",
    affected_versions=_AFFECTED,
    remove_when="Upstream declares the indexer geometry dataclass fields.",
)
def mla_attention_spec_eq(self, other):
    equal = _upstream_eq(self, other)
    if equal is NotImplemented or not equal:
        return equal
    return (self.indexer_n_head, self.indexer_q_head_dim) == (
        other.indexer_n_head,
        other.indexer_q_head_dim,
    )


@patch(
    _MODULE,
    "MLAAttentionSpec.__hash__",
    reason="Hash indexer geometry consistently with MLA spec equality.",
    affected_versions=_AFFECTED,
    remove_when="Upstream declares the indexer geometry dataclass fields.",
)
def mla_attention_spec_hash(self):
    return hash((_upstream_hash(self), self.indexer_n_head, self.indexer_q_head_dim))


def _extend_existing_subclass(cls):
    """Subclasses generated before plugin loading have their own field tables."""
    cls.__dataclass_fields__ = {
        **cls.__dataclass_fields__,
        **_IndexerGeometry.__dataclass_fields__,
    }
    original_init = cls.__init__
    original_eq = cls.__eq__
    original_hash = cls.__hash__
    metadata = dict(
        reason="Existing MLA spec subclasses must retain geometry through dataclass operations.",
        affected_versions=_AFFECTED,
        remove_when="Upstream declares the indexer geometry dataclass fields.",
    )

    def init(self, *args, indexer_n_head=None, indexer_q_head_dim=None, **kwargs):
        original_init(self, *args, **kwargs)
        object.__setattr__(self, "indexer_n_head", indexer_n_head)
        object.__setattr__(self, "indexer_q_head_dim", indexer_q_head_dim)

    def equal(self, other):
        same = original_eq(self, other)
        if same is NotImplemented or not same:
            return same
        return (self.indexer_n_head, self.indexer_q_head_dim) == (
            other.indexer_n_head,
            other.indexer_q_head_dim,
        )

    def hash_value(self):
        return hash((original_hash(self), self.indexer_n_head, self.indexer_q_head_dim))

    patch(_MODULE, f"{cls.__name__}.__init__", **metadata)(init)
    patch(_MODULE, f"{cls.__name__}.__eq__", **metadata)(equal)
    patch(_MODULE, f"{cls.__name__}.__hash__", **metadata)(hash_value)


for _subclass in MLAAttentionSpec.__subclasses__():
    if _subclass.__module__ == _MODULE:
        _extend_existing_subclass(_subclass)
