#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate the reviewable patch inventory from runtime patch metadata."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "vllm_sail" / "patch" / "manifest.md"
sys.path.insert(0, str(ROOT))

from tools._common import PatchEnvironmentError, load_patch_records  # noqa: E402


def _cell(value: str) -> str:
    return value.strip().replace("|", r"\|").replace("\n", "<br>")


def render(records: list[Any]) -> str:
    """Render records deterministically so CI can compare the committed file."""
    lines = [
        "# Runtime patch manifest",
        "",
        "Generated by `python tools/patch_manifest.py`; do not edit by hand.",
        "",
        "| Target | Kind | Reason | Affected versions | Remove when |",
        "|---|---|---|---|---|",
    ]
    for record in sorted(records, key=lambda item: item.target):
        lines.append(
            "| "
            + " | ".join(
                _cell(value)
                for value in (
                    record.target,
                    record.kind,
                    record.reason,
                    record.affected_versions,
                    record.remove_when,
                )
            )
            + " |"
        )
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify vllm_sail/patch/manifest.md without rewriting it",
    )
    args = parser.parse_args(argv)
    try:
        records = load_patch_records("patch manifest")
        expected = render(records)
    except PatchEnvironmentError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2

    if args.check:
        actual = MANIFEST.read_text(encoding="utf-8") if MANIFEST.exists() else None
        if actual != expected:
            print(
                "ERROR: vllm_sail/patch/manifest.md is stale; run "
                "`python tools/patch_manifest.py` in a real vLLM environment.",
                file=sys.stderr,
            )
            return 1
        print("vllm_sail/patch/manifest.md is up to date")
        return 0

    MANIFEST.write_text(expected, encoding="utf-8")
    print(f"wrote {MANIFEST} ({len(records)} patches)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
